apiVersion: apps/v1
kind: Deployment
metadata:
  name: calit-backend-vname
spec:
  replicas: 2
  selector:
    matchLabels:
      type: calit-backend-vname
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: calit-backend-vname
    spec:
      containers:
        - name: container
          image: minionz/calit-backend:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: DOMAIN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DOMAIN_ADDRESS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: MAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: JWT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: KAKAO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: NAVER_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: NAVER_CLIENT_ID
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: NAVER_CLIENT_SECRET
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: KAFKA_SERVER
            - name: AWS_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: AWS_ACCESSKEY
            - name: AWS_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: AWS_SECRETKEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: AWS_REGION
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: S3_BUCKET
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-vname
spec:
  selector:
    type: calit-backend-vname
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-sticky-vname
spec:
  selector:
    type: calit-backend-sticky-vname
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: ClientIP  # 스티키 세션 적용
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calit-backend-sticky-vname
spec:
  replicas: 1
  selector:
    matchLabels:
      type: calit-backend-sticky-vname
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: calit-backend-sticky-vname
    spec:
      containers:
        - name: container
          image: minionz/calit-backend:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: DOMAIN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DOMAIN_ADDRESS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: MAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: JWT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: KAKAO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: NAVER_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: NAVER_CLIENT_ID
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: NAVER_CLIENT_SECRET
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: KAFKA_SERVER
            - name: AWS_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: AWS_ACCESSKEY
            - name: AWS_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: calit-backend-secrets
                  key: AWS_SECRETKEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: AWS_REGION
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: calit-backend-configmap
                  key: S3_BUCKET
      terminationGracePeriodSeconds: 10