apiVersion: apps/v1
kind: Deployment
metadata:
  name: calit-backend-vname
spec:
  replicas: 2
  selector:
    matchLabels:
      type: calit-backend-vname
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: calit-backend-vname
    spec:
      containers:
        - name: container
          image: minionz/calit-backend:latest
          envFrom:
            - configMapRef:
                name: calit-backend-configmap
            - secretRef:
                name: calit-backend-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-vname
spec:
  selector:
    type: calit-backend-vname
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-sticky-vname
spec:
  selector:
    type: calit-backend-sticky-vname
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: ClientIP  # 스티키 세션 적용
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calit-backend-sticky-vname
spec:
  replicas: 1
  selector:
    matchLabels:
      type: calit-backend-sticky-vname
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: calit-backend-sticky-vname
    spec:
      containers:
        - name: container
          image: minionz/calit-backend:latest
          envFrom:
            - configMapRef:
                name: calit-backend-configmap
            - secretRef:
                name: calit-backend-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

      terminationGracePeriodSeconds: 10