apiVersion: apps/v1
kind: Deployment
metadata:
  name: calit-frontend-vname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calit-frontend-vname
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calit-frontend-vname
    spec:
      containers:
        - name: calit-frontend-vname
          image: minionz/calit-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config

      volumes:
        - name: nginx-config
          configMap:
            name: calit-frontend-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc-vname
spec:
  selector:
    app: calit-frontend-vname
  ports:
    - port: 80
      name: "svc80"
      targetPort: 80
  type: ClusterIP
