apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-meeting-green
spec:
  schedule: "0 */10 * * * ?" # 매 10분마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meeting-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "meetingReminderJob"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-task-green
spec:
  schedule: "0 */10 * * * ?"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meeting-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "taskReminderJob"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-sprint-green
spec:
  schedule: "0 */10 * * * ?"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meeting-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "sprintReminderJob"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure