apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-meeting
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meeting-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "meetingReminderJob"
                - name: TZ
                  value: "Asia/Seoul"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-task
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: task-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "taskReminderJob"
                - name: TZ
                  value: "Asia/Seoul"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: calit-sprint
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sprint-reminder-container
              image: minionz/calit-batch:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_BATCH_JOB_NAME
                  value: "sprintReminderJob"
                - name: TZ
                  value: "Asia/Seoul"
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_URL
                - name: DB_USERNAME
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: calit-backend-secrets
                      key: DB_PASSWORD
                - name: KAFKA_SERVER
                  valueFrom:
                    configMapKeyRef:
                      name: calit-backend-configmap
                      key: KAFKA_SERVER
          restartPolicy: OnFailure
